FROM nginx:1.18.0-alpine
COPY ./dist /usr/share/nginx/html
COPY ./k8s/nginx.conf /etc/nginx/nginx.conf
COPY ./k8s/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
